title Provide dependencies
(*) --> Scan
-->[Declarations] Group 
-->[Groups] Bind dependencies
if "Bindings are correct?" then
-->[Yes] return bidnings
--> ==END==
else 
-->[No] throw Exception
--> ==END==
-->(*)
